### ISSUE TITLE
repository not found

### ISSUE THREAD

**Issue by rafariva** [hellonico/fruits-classification#1]
the repository   http://hellonico.tokyo:8081/repository/hellonico/ not found
the deps:
 [org.hellonico/imgscalr-lib "4.2"]
[org.hellonico/sizing "0.1.0"]

could not be installed

**Comment by hellonico** [comment]
Hi there,

I had to move the repository to https some time ago. 
It's fixed on master now:

https://github.com/hellonico/fruits-classification/commit/fb507b81c9f264f7ae6d6a3b21a73aae4719462d

Nico

**Comment by rafariva** [comment]
Thanks, workds that part. will open another issue. please
